apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spam2000
  name: spam2000
spec:
  replicas: {{ .Values.spam2000.replicaCount }}
  selector:
    matchLabels:
      app: spam2000
  template:
    metadata:
      labels:
        app: spam2000
    spec:
      containers:
        - name: spam2000
          image: {{ .Values.spam2000.image }}
          ports:
            - containerPort: 3000
              protocol: TCP
          securityContext:
            runAsUser: 0 # root
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 100m
              memory: 200Mi


