apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: spam2000-monitor
  labels:
    app: spam2000
spec:
  selector:
    matchLabels:
      app: spam2000
  endpoints:
  - port: {{ .Values.spam2000.service.portName }}
    path: "/metrics"
    interval: {{ .Values.spam2000.metrics.interval }}
    scrapeTimeout: 2m
